<p>
    This allows you to add a mod that is not in the database. The Url must be from
    one of the mod sites that is supported by TES Search. Note: at this time, ElricM
    doesn't support this feature.
</p>

<p>
    It is not required to do this for every mod. The parser will auto discover
    the majority of mods. However from time to time some mods are missed. If you
    have just uploaded a mod to a mod site, please wait at least 15 days for the
    mod to become avaible. Adding it here will not make it any faster.
</p>

<p>
    This will not parse the mod immidantly. It may take some time for the result
    to become avaible on the index.
</p>

<?php echo $this->form ?>
<?php echo $this->error ?>

