<h2 align="center">TES Search</h2>

<div id="indexSearch">
    <?php
    $this->searchForm->setAction(
            $this->url(array('controller' => 'search'),'search',true)
    );
    ?>

    <?php echo $this->searchForm ?>
</div>


<div id="stats">
    <?php $stats = $this->stats(); ?>

    <table>
        <tr>
            <td>
                Unique Mods:
            </td>
            <td>
                <?php echo $stats['ModCount'] ?>
            </td>
        </tr>

        <tr>
            <td>
                Skyrim:
            </td>
            <td>
                <?php echo $stats['Games'][4] ?>
            </td>
        </tr>

        <tr>
            <td>
                Oblivion:
            </td>
            <td>
                <?php echo $stats['Games'][4] ?>
            </td>
        </tr>

        <tr>
            <td>
                Morrowind:
            </td>
            <td>
                <?php echo $stats['Games'][3] ?>
            </td>
        </tr>

        <tr>
            <td>
                Newest Mod:
            </td>
            <td>
                <?php $mod = $stats['Newest'] ?>
                <a href="mods/<?php echo $mod['id'] ?>/<?php echo $this->seoString($mod['name']) ?>">
                    <?php echo $mod['name'] ?>
                </a>
            </td>
        </tr>

    </table>
</div>

<div id="intro">
    <p>
        TES Search is a search engine that searches various Morrowind, Oblivion and Skyrim mod sites.
    </p>

    <p>

    </p>
</div>

<div align="center">
    <script type="text/javascript"><!--
        google_ad_client = "ca-pub-6883607587904275";
        /* TES Search Home */
        google_ad_slot = "0629287700";
        google_ad_width = 728;
        google_ad_height = 90;
        //-->
        </script>
        <script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>
</div>
