options:
    type: InnoDB
    collate: utf8_general_ci
    charset: utf8
# ##############################################################################
CookieJar:
    columns:
        domain:
            type: string(255)
            primary: true
        data:
            type: blob

# ##############################################################################
ErrorLog:
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
        level:
            type: integer(1)
        level_name: string(32)
        message:
            type: string
        timestamp: timestamp

# ##############################################################################
Site:
    columns:
        id:
            type: integer
            autoincrement: true

        #this is to allow looking up sites by host name
        host:
            primary: true
            type: string(255)
        
        #this is the string for the base of the url. This should be common
        #to every
        #for example: http://yacoby.silgrad.com
        base_url:
            type: string
            notnull: true

        #this is as much as the GET string as possible that is common to every mod
        #i.e. /mod.php?id=
        mod_url_prefix:
            type: string
            notnull: true

        #The limit in bytes per day that can be used
        #by the parser. This doesn't include headers
        byte_limit:
            type: integer
            default: 0

        #The number of bytes currently used
        bytes_used:
            type: integer
            default: 0
            notnull: true

        #the time the bytes were last updated
        #as it doesn't reset the bytes used at midnight
        #but rather the bytes used are reduced per at a set amount each second
        bytes_last_updated:
            type: integer
            default: 0

        next_update:
            type: integer
            default: 0
            notnull: true

        #quick way to disable parsing of a site
        enabled:
            type: boolean
            default: true
            notnull: true

    indexes:
        id:
            fields: [id]

# #############################################################################
Category:
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
        name:
            type: string
            notnull: false


# #############################################################################
Modification:
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
        name:
            type: string
            notblank: true
        author:
            type: string
            notblank: true

# #############################################################################
Game:
    columns:
        id:
            type: integer
            primary: true

            #game is not auto increment, as the games release is the id.
            #So morrowind would be 3, Ob woudl be 4
            #autoincrement: true
        short_name:
            type: string(4)
            notblank: true
        name:
            type: string
            notblank: true

    relations:
        Modification:
            foreignAlias: Games 
            class: Modification
            refClass: GameMods
# #############################################################################

GameMods:
    columns:
        game_id:
            type: integer
            primary: true
        modification_id:
            type: integer
            primary: true
    relations:
        Modification:
            foreignAlias: GameMods
        Game:
            foreignAlias: GameMods
# #############################################################################
Location:
    columns:
        modification_id:
            type: integer
            primary: true

        mod_url_suffix:
            type: string(255)
            notblank: true
            primary: true

        description:
            type: string

        version:
            type: string

        int_version:
            type: integer
        

        site_id: integer
        category_id: integer
    relations:
        Modification:
            foreignAlias: Locations
            onDelete: CASCADE
        Site:
            foreignAlias: Locations
        Category:
            foreignAlias: Locations

    indexes:
        modification_id:
            fields: [modification_id]
        #as searching involves searching for int_version == 0
        int_version:
            fields: [int_version]
# #############################################################################
Page:
    columns:
        site_id:
            type: integer
            primary: true

        #this is the whole url path, excluding the value of baseUrl from the
        #related site. NOTE: By iteslf, this is not primary
        url_suffix:
            type: string(255)
            primary: true
            notnull: true
            notblank: true
            
        last_visited:
            type: integer
            notnull: true
            default: 0
            
        revisit: integer
    indexes:
        url_suffix:
            fields: [url_suffix]

    relations:
        Site:
            foreignAlias: Pages

# #############################################################################
AditionalMods:
    columns:
        id:
            type: integer
            primary: true

        modification_id: integer

        name: string
        author: string
        url: string
        game_id: integer
    relations:
        Modification:
            type: many
            foreignType: one
        Game:
            type: many
            foreignType: one

# #############################################################################
SearchHistory:
    columns:
        id:
            type: integer
            autoincrement: true
        #this is so that one persons searches don't take over the entire recent
        #search history. You are basically allowed at maximum on one search
        #in the history
        ip:
            type: string(127)
            primary: true
        search_time: integer
        game_id: integer
        general: string
        name: string
        author: string
        description: string
    relations:
        Game:
            type: many
            foreignType: one
    indexes:
        id:
            fields: [id]

# #############################################################################
HistoryBanned:
    columns:
        ip:
            type: string(127)
            primary: true
        banned_time: integer
    relations:
        SearchHistory:
            type: one
            foreign: ip
            local: ip