<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <script type="text/javascript"
                src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js">
        </script>
        <script type="text/javascript"
                src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js">
        </script>

        <?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl(); ?>
        <script type="text/javascript"
                src="<?php echo $baseUrl ?>/minify/?g=js">
        </script>
        <link   rel="stylesheet"
                type="text/css"
                href="<?php echo $baseUrl ?>/minify/?g=css">
        </link>

        <!--
        <link rel="search"
              type="application/opensearchdescription+xml"
              title="ES Search: MW"
              href="<?php echo $baseUrl ?>/opensearch/mw.xml">
        </link>
        -->


        <?php
        if ( isset($this->index) && $this->index == false ){
            ?><meta name="robots" content="noindex" /><?php
        }
        if ( isset($this->title) ) { //Set from within the controller
            $this->headTitle($this->title);
        }

        $this->headTitle('TES Search');
        $this->headTitle()->setSeparator(' | ');

        echo $this->headTitle()
        ?>

        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-21602422-1']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

            //checking for adblock requires that the page is loaded
            $(document).ready(function(){
                var ad = $('.ad');
                if ( ad.length ){ 
                    if ( ad.height() == 0 ){
                        try{
                            _gaq.push(['_setCustomVar',
                                       1,
                                       'AdblockDetected',
                                       'True',
                                       1]);
                        }catch(err){
                        }
                    }else{
                        _gaq.push(['_setCustomVar',
                                   1,
                                   'AdblockDetected',
                                   'False',
                                   1]);
                    }
                }
                //this script has run, so we are using scripts
                _gaq.push(['_setCustomVar',
                           2,
                           'NoScript',
                           'False',
                           1]);

                //this actually makes the call to ga, so this needs to be pushed
                //last
                _gaq.push(['_trackPageview']);
            });
        </script>
    </head>

    <body>
        <noscript>
            <div id="noscriptWarning">
                TES Search works best with JavaScript enabled
            </div>
            <div id="noscriptPadding">
                &nbsp;
            </div>

        </noscript>


        <div id="header">
            <a href="<?php echo $this->url( array(
                                                'controller'=>'index',
                                                'action' => null
                                            ),
                                            'default')?>">
                TES Search</a>
        </div>

        <div style="margin: 5px 0 20px;">
            <div class="line"></div>
        </div>

        <div id="content">
            <?php echo $this->layout()->content ?>
        </div>

        <div id="recentSearch">

            <div style="margin:5px 0">
                <div class="line"></div>
            </div>

            <div style="white-space:nowrap; overflow: hidden;">
                Recent Searches: <?php echo $this->recentSearches() ?>
            </div>

            <div style="margin: 5px 0 20px;">
                <div class="line"></div>
            </div>
        </div>

        <div id="footer">
            <div>
                <a href="<?php echo $this->url(
                        array('controller'=>'info','action' => 'about'),
                        'default'
                )?>"> About </a> -
                <a href="<?php echo $this->url(
                        array('controller'=>'info','action' => 'credits'),
                        'default'
                )?>"> Credits </a> -
                <a href="<?php echo $this->url(
                        array('controller'=>'info','action' => 'bug'),
                        'default'
                )?>"> Report Bug </a> -
                <a href="<?php echo $this->url(
                        array('controller'=>'info','action' => 'feature'),
                        'default'
                )?>"> Request Feature </a> <!-- -
                <a href="<?php echo $this->url(
                        array('controller'=>'mod','action' => 'add'),
                        'default'
                )?>"> Add Mod </a>
                                           -->
            </div>

            <div id="cpy">
                Design Copyright &copy; Jacob Essex 2011.
                Mod details and descriptions are owned by its author(s)
            </div>
        </div>


    <noscript> 
    <?php 
        //some fairly basic code to track people who have JavaScript disabled
        //and so the more detailed ga.js can't be used.
                
        //http://code.google.com/apis/analytics/docs/concepts/gaConceptsOverview.html
        $query = array('utmac'  => 'UA-21602422-1', //account string
                       //'utmcc'  => ,//cookie values
                       //'utmcs'  => ,//encoding
                       'utmdt'  => $this->headTitle() ,//page title
                       'utmr'   => isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '',
                       'utme'   => '8(NoScript)9(True)11(1)', //extensible paramter
                       'utmhn'  => $_SERVER['HTTP_HOST'], //hostname
                       'utmhid' => rand(),
                       //'utmul'  => , //language
                       'utmp'   => $_SERVER['REQUEST_URI'], //page request
                   );
        $queryStr = http_build_query($query);
        $url = 'http://www.google-analytics.com/__utm.gif?' . $queryStr;

        echo '<img src="'. $url .'" border="0" />'; 
    ?> 
    </ noscript>

    </body>

</html>
