<h3>About</h3>

<p>
    ES Search is a project that grew out of a small PHP script. It has undergone
    successive re-writes until it is what it is today.
</p>

<p>
    It is for legacy reasons written in PHP, but searching is now done using
    Sphinx as the full text search engine. The code uses the 
    <a href="http://framework.zend.com/" target="_blank">Zend Framework</a> and
    (again for legacy reasons) the 
    <a href="http://simplehtmldom.sourceforge.net/" target="_blank">Simple HTML DOM</a> library
    for parsing. A move to xpath is now being made give how resource hungry building
    a dom is in PHP.
</p>

<p>
    The most recent version (most of the time slightly newer than the online
    versions) is
    <a href="https://github.com/Yacoby/es-search" target="_blank">hosted at
        Github</a> under the AGPL3 licence. 
</p>
