<h3>:-(</h3>
<p>
You probably have some sort of ad blocking enabled:</b>

<strong>td;dr</strong><br />:

Enable Ads (for this site) - Disable this message
</p>

<h4>More information</h4>
<p>
I run this server out of my own pocket. It doesn't cost much to run but then
ads don't provide me with much (I am not making a profit).<br />

View it as a sort of micro transaction, you view the ad and hopefully get
good search results, I get a small amount of money at no cost to yourself.
</p>

<p>
Hence, I would be much obliged if you would <em>consider</em> enabling ads for 
this site. This interface sets a cookie, far better to ad an exception in your
ad blocker
</p>

<p>
Enable Ads (for this site) - Disable this message
</p>
