<h3>Report Bug</h3>

<p>
    Before you report a bug
</p>
<ul>
    <li>
        Make sure you have cleared your browser cache
    </li>
    <li>
        Make sure it is re-porduceable
    </li>
    <li>
        Make sure it
        <a href="http://code.google.com/p/es-search/issues/list?can=2&q=label%3ADefect" target="_blank">
            hasn't been reported already</a>
    </li>
</ul>
<p>
    Once you have done all the steps, report it
    <a href="http://code.google.com/p/es-search/issues/entry" target="_blank">
        on the issue tracker</a>
</p>
