<h3>Request Feature</h3>
<p>
If you want to request a feature, first ensure that the feature hasn't already
been requested by <a href="https://github.com/Yacoby/es-search/issues"
                     target="_blank">looking over the list</a>
</p>

<p>
    If you are sure the feature doesn't exist, you can add the feature
    via <a href="https://github.com/Yacoby/es-search/issues" target="_blank">
        the issue tracker</a>.
</p>

<p>
    If the feature has already been requested and hasn't been done, consider
    doing it yourself rather than wait for me to do it
</p>
