<h3>Request Feature</h3>
<p>
If you want to request a feature, first ensure that the feature hasn't already
been requested by <a href="http://code.google.com/p/es-search/issues/list?can=2&q=label%3AEnhancement"
                     target="_blank">looking over the list</a>
</p>

<p>
    If you are sure the feature doesn't exist, you can add the feature
    via <a href="http://code.google.com/p/es-search/issues/entry" target="_blank">
        the issue tracker</a>. Be sure to flag it as feature as Type-Enhancement
</p>

<p>
    If the feature has already been requested and hasn't been done, consider
    doing it yourself rather than wait for me to do it
</p>
