  <h1>An error occurred</h1> 
  <h2><?php echo $this->message ?></h2>
  <?php if ( APPLICATION_ENV == 'development' || APPLICATION_ENV == 'testing'): ?>
  
  <h3>Exception information:</h3> 
  <p> 
      <b>Message:</b> <?php echo $this->exception->getMessage() ?> 
  </p> 

  <h3>Stack trace:</h3> 
  <pre><?php echo $this->exception->getTraceAsString() ?> 
  </pre> 

  <h3>Request Parameters:</h3> 
  <pre><?php var_dump($this->request->getParams()) ?> 
  </pre> 
  <?php endif ?>
  
<?
    Search_PageCache::getInstance()->cancel();
?>
