#!/usr/bin/env php
<?php
define('APPLICATION_ENV', 'development');
/**
 * CLI Script
 */
require dirname(__FILE__).'/../AppLoader.php';


 error_reporting(E_ALL | E_STRICT);
 ini_set("display_errors", 1);

$app = createApplication();
$cli = new Doctrine_Cli(Zend_Registry::get('doctrine_config'));
$cli->run($_SERVER['argv']);
